### PR TITLE
Add Mash Step

### PR DESCRIPTION
**Pull request by chappo**
Added Mash Step Task to turn actor on until a certain weight is reached. 

Only feature I was unable to add but is currently in the Config screen for the Mash Step is a Tare Function. Can we just call the function already created on the previous step? My python isn't up to the task (I am sure its simple)..

### CODE REVIEW

**Comment by chappo** [comment]
Alexander,

Was getting an error on any values for Offset & Scale --  _invalid literal for int() with base 10_

**Comment by avollkopf** [comment]
@chappo I have added you as collaborator as I cannot test these things since I don't have the weight cell included in my system. You should now also be able to merge.

**Comment by chappo** [comment]
Thanks @avollkopf. Can you confirm how we would access the tare function from within the mash step? Only feature I would like to see added but unsure how to call that function.

**Comment by avollkopf** [comment]
The reset might need to be done like in the flowmeter.
1.  add a fucntion for reset and call this function from the action 
```
    @action(key="Tare Sensor", parameters=[])
    async def Reset(self, **kwargs):
       self.reset()
```

```
 def reset(self):
        self.hx.tare()
        logging.info("Tare HX711 Loadcell")
```


In the step call:
```

        if self.resetsensor == "Yes":
            self.sensor.instance.reset()
```

**Pull request merged**
